import Link from "next/link";
import { Waves } from "lucide-react";
import { Container } from "@/components/ui/Container";

export function Footer() {
  return (
    <footer className="border-t border-navy/10 bg-navy text-warm/80">
      <Container className="grid gap-8 py-12 sm:grid-cols-3">
        <div>
          <div className="flex items-center gap-2 font-serif text-lg font-semibold text-white">
            <span className="flex h-8 w-8 items-center justify-center rounded-full bg-adriatic">
              <Waves className="h-4 w-4 text-white" aria-hidden="true" />
            </span>
            Adria Stay Budva
          </div>
          <p className="mt-3 max-w-xs text-sm leading-relaxed text-warm/60">
            A boutique one-bedroom apartment in Budva, Montenegro. Hosted directly, answered instantly.
          </p>
        </div>

        <div>
          <p className="text-xs font-semibold uppercase tracking-wide text-warm/40">Explore</p>
          <ul className="mt-3 space-y-2 text-sm">
            <li><a href="#overview" className="hover:text-white">Overview</a></li>
            <li><a href="#amenities" className="hover:text-white">Amenities</a></li>
            <li><a href="#gallery" className="hover:text-white">Gallery</a></li>
            <li><a href="#location" className="hover:text-white">Location</a></li>
            <li><a href="#reviews" className="hover:text-white">Reviews</a></li>
          </ul>
        </div>

        <div>
          <p className="text-xs font-semibold uppercase tracking-wide text-warm/40">For the owner</p>
          <ul className="mt-3 space-y-2 text-sm">
            <li>
              <Link href="/dashboard" className="hover:text-white">
                Owner dashboard →
              </Link>
            </li>
          </ul>
          <p className="mt-4 text-xs leading-relaxed text-warm/40">
            This is a Phase 1 product demo. Chat replies are generated by a deterministic mock assistant —
            no AI API is used yet.
          </p>
        </div>
      </Container>

      <div className="border-t border-white/10 py-5">
        <Container className="flex flex-col gap-2 text-xs text-warm/40 sm:flex-row sm:items-center sm:justify-between">
          <p>© {new Date().getFullYear()} Adria Stay Budva — demo project.</p>
          <p>Budva, Montenegro</p>
        </Container>
      </div>
    </footer>
  );
}
